---
- name: Disable Packages
  ignore_errors: true
  yum:
    name: 
    - rsh
    - telnet-client
    state: absent

- name: Install OS Packages
  ignore_errors: true
  yum:
    name: 
    - rsyslog
    - sysstat
    - aide
    state: latest

